[package]
name = "ebmeta"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.38.4", features = ["serde", "serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
zip = "7.0.0"
