[package]
name = "ebmeta"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
id3 = "1.16.3"
mp4ameta = "0.13.0"
quick-xml = { version = "0.38.4", features = ["serde", "serialize"] }
serde = { version = "1.0", features = ["derive"] }
zip = "7.0.0"
