[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
print_stdout = "warn"
print_stderr = "warn"
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
collapsible_if = "warn"
collapsible_else_if = "warn"
if_not_else = "warn"
manual_let_else = "warn"
redundant_closure_for_method_calls = "warn"
map_unwrap_or = "warn"
filter_map_next = "warn"
implicit_clone = "warn"
needless_pass_by_value = "warn"
semicolon_if_nothing_returned = "warn"
match_bool = "warn"